# THIS IS AN AUTOGENERATED FILE! DO NOT EDIT HERE DIRECTLY! USE build.py fot this

from setuptools import setup, find_packages

setup(
    name="horst",
    version="0.0.1",
    description="Horst is a simple build-automation-tool for python packages",
    long_description="",
    url="",
    packages=['horst', 'horst.runner', 'horst.integration_test', 'horst.tests']
)