import pytest
from os import path

from horst import Horst
from horst.build import from_git_config, _render_setuppy


@pytest.fixture()
def horst():
    build_py = path.abspath(path.join(path.dirname(__file__), "..", "..", "build.py"))
    horst = Horst("")
    horst._invalidate()
    yield Horst(build_py)
    horst._invalidate()


def test_from_git_with_existing_value(horst):
    config = from_git_config("bare")
    assert config == {"bare": "false"}


def test_from_git_not_existing_value(horst):
    config = from_git_config("not-existing-key")
    assert config == {}


def test_format_setup_py_template():
    rendred_setuppy = _render_setuppy(dict(
        name="horst",
        version="1",
        description="short",
        long_description="long",
        url="/url/to",
    ))
    expected_text = """# THIS IS AN AUTOGENERATED FILE! DO NOT EDIT HERE DIRECTLY! USE build.py fot this

from setuptools import setup, find_packages

setup(
    name="horst",
    version="1",
    description="short",
    long_description="long",
    url="/url/to"
"""
    assert rendred_setuppy.startswith(expected_text)